# E2E contract for the `beehave check` CLI command (v3.0.0).
#
# `beehave check` is a single static gate:
#   1. Per-feature: derive expected `def test_<slug>(params) -> None` lines
#      from the feature source, parse the matching `tests/features/*_test.py`
#      modules' AST, return False if expected set != actual non-private
#      function signature set.
#   2. Orphan module: a `*_test.py` in `tests/features/` whose stem does not
#      correspond to any feature's expected module → exit 1.
# Private functions (leading `_`) are exempt — part of the consumer's
# superset (helpers, fixtures wrappers). Step-body / parametrize-row
# enforcement is the runtime `step` CM's job (Mode B).

HIVE_ACTIVITY_FEATURE: str

def copy_feature_into_pytester(pytester, basename: str) -> str: ...
def write_feature_text(pytester, basename: str, text: str) -> str: ...
def run_beehave_check(pytester, *args: str) -> int: ...
def test_check_passes_on_freshly_generated_project(pytester) -> None: ...
def test_check_fails_when_py_missing_scenario_fn(pytester) -> None: ...
def test_check_fails_on_orphan_module_in_tests_features(pytester) -> None: ...
def test_check_ignores_handwritten_py_outside_tests_features(pytester) -> None: ...
def test_check_fails_when_py_fn_signature_drifts(pytester) -> None: ...
def test_check_passes_with_private_helpers_in_py(pytester) -> None: ...
def test_check_fails_when_py_has_extra_non_private_fn(pytester) -> None: ...
def test_check_scoped_to_one_feature_path(pytester) -> None: ...
def test_check_scoped_skips_orphan_module_detection(pytester) -> None: ...
def test_check_scoped_fails_on_drift_in_targeted_feature(pytester) -> None: ...
def test_check_scoped_fails_on_nonexistent_path(pytester) -> None: ...
def test_check_scoped_fails_on_non_feature_file(pytester) -> None: ...
