# E2E contract for the `beehave check` CLI command.
#
# Drives the CLI through the pytester subprocess. Asserts the structural-binding
# gate (the v2 CIT-rooted contract): the test body's `with step(...)` blocks in
# source order match the parsed `.feature` steps `block[i] <-> step[i]` on
# exactly three fields - `(keyword, text, placeholder-name-set)` - and NOTHING
# else. Body content is deferred to the review gate. Keyword matching is
# case-insensitive. Literal/placeholder AST appearance is NOT inspected
# (v1 noise loophole closed).

# Fixture feature basenames available under docs/features/.
HIVE_ACTIVITY_FEATURE: str
COMB_CONSTRUCTION_FEATURE: str

def copy_feature_into_pytester(pytester, basename: str) -> str: ...
def write_feature_text(pytester, basename: str, text: str) -> str: ...
def write_test_py(pytester, stem: str, body: str) -> str: ...
def run_beehave_check(pytester, *args: str) -> int: ...
def test_passes_when_blocks_match_steps(pytester) -> None: ...
def test_fails_when_block_count_differs_from_step_count(pytester) -> None: ...
def test_fails_when_step_keyword_structurally_mismatches(pytester) -> None: ...
def test_fails_when_step_text_mismatches(pytester) -> None: ...
def test_fails_when_placeholder_name_set_mismatches(pytester) -> None: ...
def test_passes_when_keyword_case_differs(pytester) -> None: ...
def test_passes_with_arbitrary_body_content_inside_step_block(pytester) -> None: ...
def test_does_not_inspect_body_for_literals_or_placeholders(pytester) -> None: ...
def test_check_fails_on_orphan_py_in_tests_features(pytester) -> None: ...
def test_check_ignores_handwritten_py_outside_tests_features(pytester) -> None: ...
