# E2E contract for the `beehave check` CLI command (v2.3.0).
#
# `beehave check` is a two-layer static gate:
#   1. stubtest on tests/features/*_test.py (catches .py ↔ .pyi signature drift)
#   2. regenerate-and-diff (regenerates expected .pyi signatures from the
#      feature, confirms they appear in the on-disk stub text)
# Plus an orphan pass: .py without .pyi sibling in tests/features/ → exit 1.
# Step-body / parametrize-row enforcement is the runtime `step` CM's job.

HIVE_ACTIVITY_FEATURE: str

def copy_feature_into_pytester(pytester, basename: str) -> str: ...
def write_feature_text(pytester, basename: str, text: str) -> str: ...
def run_beehave_check(pytester, *args: str) -> int: ...
def test_check_passes_on_freshly_generated_project(pytester) -> None: ...
def test_check_fails_when_pyi_stale_after_feature_adds_scenario(pytester) -> None: ...
def test_check_fails_on_orphan_py_in_tests_features(pytester) -> None: ...
def test_check_ignores_handwritten_py_outside_tests_features(pytester) -> None: ...
def test_check_fails_when_py_drifts_from_pyi(pytester) -> None: ...
