# E2E contract for the `beehave generate` CLI command.
#
# Drives the CLI through the pytester subprocess against `docs/features/*.feature`
# and asserts the observable emission surface:
#   - `<feature>_default_test.py` plus one `<feature>_<rule>_test.py` per Rule;
#   - the `.py` skeleton is emitted only when absent (idempotency);
#   - no `.pyi` files are emitted (v3.0.0 dropped consumer-side stubtest);
#   - Scenario title -> `test_<slug>` function name (slug = lowercased title,
#     whitespace runs collapsed to a single underscore);
#   - Feature and Rule Background steps are prepended to every relevant
#     scenario's `with step(...)` block list in the emitted `.py`;
#   - tags, step-docstrings, and step-data-tables are parsed (Full Gherkin)
#     and surface as `pytestmark` / `@pytest.mark.<tag>` decorators and
#     body-local variables (`docstring = '...'`, `data_table = [...]`).

# Fixture feature basenames available under docs/features/ (the v2 E2E inputs).
HIVE_ACTIVITY_FEATURE: str
COMB_CONSTRUCTION_FEATURE: str
TITLE_VALIDATION_FEATURE: str
STATUS_COMMAND_FEATURE: str
CASE_INSENSITIVE_MATCHING_FEATURE: str

# Default-group suffix in the per-rule emission convention
# `<feature_slug>_<rule_slug>_test.py`.
DEFAULT_GROUP_SUFFIX: str

# The directory `generate` emits `*_test.py` into (pyproject testpaths).
EMISSION_DIR: str

def copy_feature_into_pytester(pytester, basename: str) -> str: ...
def write_feature_text(pytester, basename: str, text: str) -> str: ...
def run_beehave_generate(pytester, *args: str) -> int: ...
def read_emitted_py(pytester, stem: str) -> str: ...
def list_emitted_stems(pytester) -> list[str]: ...
def test_emits_py_for_default_group_and_each_rule(pytester) -> None: ...
def test_always_emits_py_file_for_every_rule_and_default(pytester) -> None: ...
def test_emits_py_skeleton_only_when_py_absent(pytester) -> None: ...
def test_scenario_title_emits_test_underscore_slug_function(pytester) -> None: ...
def test_function_name_carries_no_uppercase_and_collapses_whitespace(
    pytester,
) -> None: ...
def test_feature_background_steps_appear_in_every_emitted_scenario(
    pytester,
) -> None: ...
def test_rule_background_steps_appear_only_in_that_rule_scenarios(pytester) -> None: ...
def test_feature_tags_surface_as_pytestmark_in_py(pytester) -> None: ...
def test_scenario_tags_surface_as_decorator_marks(pytester) -> None: ...
def test_step_docstring_surfaces_as_body_local_var(pytester) -> None: ...
def test_step_data_table_surfaces_as_body_local_var(pytester) -> None: ...
def test_generate_creates_tests_features_dir_if_absent(pytester) -> None: ...
def test_outline_scenario_emits_parametrize_in_py(pytester) -> None: ...
def test_generate_does_not_emit_pyi_files(pytester) -> None: ...
