# E2E contract for the `beehave status` CLI command.
#
# The interview named `status` as one of three CLI commands but flagged its
# detailed behaviour as SOFT (no CIT incident, no laddered constraint grounded
# what it reports). The minimal falsifiable claim - asserted here - is that
# `status` derives a small, deterministic report from disk state without
# stored mutable state of its own:
#   - exit 0 when the features directory exists;
#   - stdout includes the count of `.feature` files discovered;
#   - stdout includes the count of emitted `*_test.pyi` stubs;
#   - exit 2 when the features directory is missing (filesystem error).
# The rich v1 stage taxonomy (broken / needs-tests / needs-bodies / needs-fixes
# / ok) is DROPPED - ungrounded by v2 CIT/laddering, and not asserted here.

def write_feature_text(pytester, basename: str, text: str) -> str: ...
def write_pyi_stub(pytester, stem: str) -> str: ...
def run_beehave_status(pytester, *args: str) -> int: ...
def status_stdout(pytester) -> str: ...
def test_status_exits_zero_when_features_dir_exists(pytester) -> None: ...
def test_status_reports_feature_file_count(pytester) -> None: ...
def test_status_reports_emitted_stub_count(pytester) -> None: ...
def test_status_exits_two_when_features_dir_missing(pytester) -> None: ...
