from __future__ import annotations

OUTLINE_FEATURE: str
PLAIN_FEATURE: str
PLAIN_FEATURE_WITH_ANGLE: str
MULTI_TABLE_FEATURE: str
DIFFERENT_TAG_TABLES_FEATURE: str

def _emitted_py(feature_text: str) -> str: ...
def test_examples_scenario_emits_parametrize_decorator() -> None: ...
def test_parametrize_arg_names_match_examples_headers() -> None: ...
def test_parametrize_rows_match_examples_rows() -> None: ...
def test_no_examples_scenario_emits_no_parametrize() -> None: ...
def test_plain_scenario_treats_angle_as_literal_text() -> None: ...
def test_multiple_examples_tables_are_merged() -> None: ...
def test_different_tagged_tables_emit_pytest_param() -> None: ...
def test_check_passes_on_freshly_generated_py() -> None: ...
