from __future__ import annotations

from pathlib import Path

OUTLINE_FEATURE: str
PLAIN_FEATURE: str

def _emit(root: Path, feature_text: str) -> tuple[str, str]: ...
def _emitted_py(feature_text: str) -> str: ...
def _emitted_pyi(feature_text: str) -> str: ...
def _check_result(feature_text: str, test_py_text: str) -> bool: ...
def test_examples_scenario_emits_parametrize_decorator() -> None: ...
def test_parametrize_arg_names_match_examples_headers() -> None: ...
def test_parametrize_rows_match_examples_rows() -> None: ...
def test_no_examples_scenario_emits_no_parametrize() -> None: ...
def test_pyi_signature_carries_str_params_for_outline() -> None: ...
def test_check_passes_when_parametrize_matches_examples() -> None: ...
def test_check_fails_when_examples_present_but_no_parametrize() -> None: ...
def test_check_fails_when_parametrize_rows_differ() -> None: ...
def test_check_fails_when_parametrize_arg_names_differ() -> None: ...
