# Integration contract for the generate -> check round-trip (v2.3.0).
#
# `generate` emits a `.pyi` (always) and a `.py` skeleton (when absent);
# `check` is signature-only — it regenerates expected `.pyi` signatures from
# the feature in-memory and confirms they appear in the on-disk stub text.
# No AST walk of the `.py` body; step/parametrize enforcement is the runtime
# `step` CM's job (Mode B).

ROUND_TRIP_FEATURE: str

def emit_test_pyi_for(feature_text: str) -> str: ...
def check_passes_for(feature_text: str, stub_text: str) -> bool: ...
def test_check_passes_on_freshly_generated_pyi() -> None: ...
def test_check_fails_when_pyi_missing_signature() -> None: ...
def test_check_fails_when_pyi_signature_renamed() -> None: ...
