# Integration contract for the generate -> check round-trip (v3.0.0).
#
# `generate` emits only a `.py` skeleton (when absent); `check` is a 1-1
# signature check — it parses the `.py` AST, collects non-private top-level
# function signatures, and verifies the set exactly equals the feature-derived
# signature set. Private functions are exempt (superset). Step/parametrize
# enforcement is the runtime `step` CM's job (Mode B).

ROUND_TRIP_FEATURE: str

def emit_test_py_for(feature_text: str) -> str: ...
def check_passes_for(feature_text: str, py_text: str) -> bool: ...
def test_check_passes_on_freshly_generated_py() -> None: ...
def test_check_fails_when_py_missing_signature() -> None: ...
def test_check_fails_when_py_signature_renamed() -> None: ...
