# Integration contract for the `step` context manager - the v2 runtime core.
#
# `from beehave import step` - `step(keyword: str, text: str, /, **placeholders)`
# is the executable `with` block that replaces v1's step-definition registry.
# The block RUNS real test code; the `Then` block asserts the outcome; the
# context manager attributes any exception to its step via
# `e.add_note(f"{keyword} {text}")` on `__exit__`, then propagates the exception.
#
# These tests drive the CM in-process; the SUT import lives in each body
# (deferred), so the `.pyi` does not import beehave.

# The exact `add_note` format the CM appends on `__exit__` exception.
NOTE_FORMAT: str

def test_block_body_executes_when_entered() -> None: ...
def test_assertion_inside_then_step_propagates_failure() -> None: ...
def test_assertion_inside_then_step_passes_when_truthy() -> None: ...
def test_exception_attributed_to_step_via_add_note() -> None: ...
def test_clean_exit_does_not_add_attribution_note() -> None: ...
def test_keyword_and_text_are_positional_only() -> None: ...
def test_placeholders_accepted_as_keyword_arguments() -> None: ...
def test_all_gherkin_step_keywords_accepted() -> None: ...
def test_localized_keyword_accepted() -> None: ...
