# Integration contract for title -> slug -> function_name derivation.
#
# The function name IS the scenario's identity (interview L1) - title -> slug
# (lowercased, whitespace runs collapsed to a single underscore) ->
# `test_<slug>`. Title rules kept from v1: case-insensitive uniqueness across
# feature/rule/scenario, a 2-6 word-count bound, and a Unicode
# letters/digits/spaces charset.
#
# These tests drive `beehave.gherkin` (parser + title-rule enforcement)
# in-process; the SUT imports live in each body (deferred), so the `.pyi`
# does not import beehave.

# Title-rule bounds (locked here so each assertion carries the domain value).
MIN_WORD_COUNT: int
MAX_WORD_COUNT: int

def function_name_for_title(title: str) -> str: ...
def title_is_valid_in_feature(*titles: str) -> bool: ...
def test_title_lowered_to_slug() -> None: ...
def test_whitespace_runs_collapse_to_single_underscore() -> None: ...
def test_function_name_is_test_underscore_slug() -> None: ...
def test_two_word_title_is_valid() -> None: ...
def test_six_word_title_is_valid() -> None: ...
def test_one_word_title_rejected() -> None: ...
def test_seven_word_title_rejected() -> None: ...
def test_title_with_hyphen_rejected() -> None: ...
def test_duplicate_titles_case_insensitive_rejected() -> None: ...
