Feature: id-generation — assign @id tags to untagged Examples

  Assigns stable, unique 8-character lowercase hex @id tags to any Example in a .feature file
  that does not already have one. beehave writes the tag back in-place, preserving all
  whitespace and formatting exactly. Any existing non-empty @id value — regardless of format —
  is treated as valid and never replaced. Only an @id with an empty value is treated as missing
  and replaced. The 8-char hex format is a beehave convention, not an enforced constraint.

  Status: BASELINED (2026-04-22)

  Rules (Business):
  - @id values are unique project-wide across all .feature files
  - Any non-empty @id value is respected as-is, regardless of format — beehave never validates or changes it
  - Only an @id with an empty value is treated as missing and replaced
  - Collision on generation triggers a silent retry until a unique id is produced
  - Assignment is top-to-bottom within each file

  Constraints:
  - In-place write preserves all existing whitespace and formatting
  - Dry-run / preview is provided by beehave status, not a separate mode

  Rule: ID assignment
    As a developer
    I want beehave to assign @id tags to untagged Examples automatically
    So that every Example has a stable identity without manual effort

    @id:1856a053
    Example: Untagged Example receives a beehave-generated @id
      Given a .feature file with an Example that has no @id tag
      When beehave assigns IDs
      Then the Example receives an @id tag whose value is exactly 8 lowercase hex characters

    @id:f381c49d
    Example: @id tag is inserted immediately before the Example keyword
      Given a .feature file with an untagged Example
      When beehave assigns IDs
      Then the @id tag appears on the line immediately before the Example: keyword

    @id:782a622b
    Example: Assignment processes Examples top-to-bottom within a file
      Given a .feature file with three untagged Examples
      When beehave assigns IDs
      Then all three Examples receive @id tags in the order they appear in the file

  Rule: ID stability
    As a developer
    I want existing @id tags to be preserved regardless of their format
    So that human-assigned IDs like @id:N001 are never overwritten by beehave

    @id:875c5c0b
    Example: Beehave-generated hex @id is not replaced on re-run
      Given an Example with @id:a1b2c3d4 (a beehave-generated value)
      When beehave assigns IDs
      Then the @id value remains a1b2c3d4

    @id:67f7cfa4
    Example: Human-assigned non-hex @id is respected as-is
      Given an Example with @id:N001 (a human-assigned value)
      When beehave assigns IDs
      Then the @id value remains N001 and is not replaced

    @id:e438b0e0
    Example: Empty @id tag is replaced with a beehave-generated value
      Given an Example with @id: (no value after the colon, only whitespace)
      When beehave assigns IDs
      Then the empty tag is replaced with an 8-char lowercase hex value generated by beehave

  Rule: Project-wide uniqueness
    As a developer
    I want @id values to be unique across all .feature files in the project
    So that test function names are unambiguous project-wide

    @id:55a83d81
    Example: Generated IDs do not collide with existing IDs in other files
      Given two .feature files each containing Examples with @id tags
      When beehave assigns IDs to a third file with untagged Examples
      Then none of the new IDs match any existing ID across all files

    @id:2d6c532a
    Example: Duplicate @id found across files is reported
      Given two .feature files where both contain an Example with the same @id value
      When beehave loads the project
      Then beehave reports the duplicate @id and both file paths according to the on_duplicate_id policy

  Rule: In-place write fidelity
    As a developer
    I want beehave to preserve all formatting when writing @id tags
    So that diffs are minimal and other content is never accidentally changed

    @id:84695ed3
    Example: Only @id tag lines are added; all other lines are unchanged
      Given a .feature file with one untagged Example
      When beehave assigns IDs
      Then the file differs from the original by exactly one inserted line containing the @id tag
